In [1]:
# Prepare a sample corpus
# A corpus is typically a collection of text documents usually belonging to one/more subjects/domains
import pandas as pd
import numpy as np

pd.options.display.max_colwidth = 200

corpus = ['The sky is blue and beautiful.',
          'Love this blue and beautiful sky!',
          'The quick brown fox jumps over the lazy dog.',
          "A king's breakfast has sausages, ham, bacon, eggs, toast and beans",
          'I love green eggs, ham, sausages and bacon!',
          'The brown fox is quick and the blue dog is lazy!',
          'The sky is very blue and the sky is very beautiful today',
          'The dog is lazy but the brown fox is quick!']

labels = ['weather', 'weather', 'animals', 'food', 'food', 'animals', 'weather', 'animals']

corpus = np.array(corpus)
corpus_df = pd.DataFrame({'Document': corpus, 'Category': labels})

corpus_df = corpus_df[['Document', 'Category']]
print(corpus_df)

                                                             Document Category
0                                      The sky is blue and beautiful.  weather
1                                   Love this blue and beautiful sky!  weather
2                        The quick brown fox jumps over the lazy dog.  animals
3  A king's breakfast has sausages, ham, bacon, eggs, toast and beans     food
4                         I love green eggs, ham, sausages and bacon!     food
5                    The brown fox is quick and the blue dog is lazy!  animals
6            The sky is very blue and the sky is very beautiful today  weather
7                         The dog is lazy but the brown fox is quick!  animals


In [2]:
# Simple text pre-processing
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mac\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mac\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [3]:
import nltk
import re

stop_words = nltk.corpus.stopwords.words('english')

def normalize_document(doc):
    # Lower case and remove special characters/whitespaces
    doc = re.sub(r'[^a-zA-Z\s]', '', doc, re.I|re.A)
    doc = doc.lower()
    doc = doc.strip()
    # Tokenize document
    tokens = nltk.word_tokenize(doc)
    # Filter stopwords out of document
    filtered_tokens = [token for token in tokens if token not in stop_words]
    # Re-create document from filtered tokens
    doc = ' '.join(filtered_tokens)
    return doc

normalize_corpus = np.vectorize(normalize_document)

norm_corpus = normalize_corpus(corpus)
print(norm_corpus)

['sky blue beautiful' 'love blue beautiful sky'
 'quick brown fox jumps lazy dog'
 'kings breakfast sausages ham bacon eggs toast beans'
 'love green eggs ham sausages bacon' 'brown fox quick blue dog lazy'
 'sky blue sky beautiful today' 'dog lazy brown fox quick']


In [ ]:
# Bag of Words model
# The bag of words model represents each text document as a numeric vector where each dimension is a specific word from the corpus and the value could be its frequency in the document, occurrence (denoted by 1 or 0) or even weighted values. 
# The model’s name is such because each document is represented literally as a ‘bag’ of its own words, disregarding word orders, sequences and grammar.

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(min_df=0., max_df=1.)
cv_matrix = cv.fit_transform(norm_corpus)
cv_matrix = cv_matrix.toarray()
print(cv_matrix)

[[0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 0 0 0 0]
 [1 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 1]
 [0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0]]


In [5]:
# Get all unique words in the corpus
vocab = cv.get_feature_names()
# Show document feature vectors
pd.DataFrame(cv_matrix, columns=vocab)

bacon  beans  beautiful  blue  breakfast  brown  dog  eggs  fox  green  \
0      0      0          1     1          0      0    0     0    0      0   
1      0      0          1     1          0      0    0     0    0      0   
2      0      0          0     0          0      1    1     0    1      0   
3      1      1          0     0          1      0    0     1    0      0   
4      1      0          0     0          0      0    0     1    0      1   
5      0      0          0     1          0      1    1     0    1      0   
6      0      0          1     1          0      0    0     0    0      0   
7      0      0          0     0          0      1    1     0    1      0   

   ham  jumps  kings  lazy  love  quick  sausages  sky  toast  today  
0    0      0      0     0     0      0         0    1      0      0  
1    0      0      0     0     1      0         0    1      0      0  
2    0      1      0     1     0      1         0    0      0      0  
3    1      0      1     0     0      0         1    0      1      0  
4    1      0      0     0     1      0         1    0      0      0  
5    0      0      0     1     0      1         0    0      0      0  
6    0      0      0     0     0      0         0    2      0      1  
7    0      0      0     1     0      1         0    0      0      0

In [ ]:
# Bag of N-grams model
# A word is just a single token, often known as a unigram/1-gram. 
# An N-gram is basically a collection of word tokens from a text document such that these tokens are contiguous & occur in a sequence. 
# Bi-grams indicate n-grams of order 2 (2 words), Tri-grams indicate n-grams of order 3 (3 words) & so on. 
# The Bag of N-Grams model is hence just an extension of the Bag of Words model so we can also leverage N-gram based features.

In [8]:
# We can set the n-gram range to 1, 2 to get unigrams as well as bigrams
bv = CountVectorizer(ngram_range=(2, 2))
bv_matrix = bv.fit_transform(norm_corpus)

bv_matrix = bv_matrix.toarray()
vocab = bv.get_feature_names()
pd.DataFrame(bv_matrix, columns=vocab)

bacon eggs  beautiful sky  beautiful today  blue beautiful  blue dog  \
0           0              0                0               1         0   
1           0              1                0               1         0   
2           0              0                0               0         0   
3           1              0                0               0         0   
4           0              0                0               0         0   
5           0              0                0               0         1   
6           0              0                1               0         0   
7           0              0                0               0         0   

   blue sky  breakfast sausages  brown fox  dog lazy  eggs ham  ...  lazy dog  \
0         0                   0          0         0         0  ...         0   
1         0                   0          0         0         0  ...         0   
2         0                   0          1         0         0  ...         1   
3         0                   1          0         0         0  ...         0   
4         0                   0          0         0         1  ...         0   
5         0                   0          1         1         0  ...         0   
6         1                   0          0         0         0  ...         0   
7         0                   0          1         1         0  ...         0   

   love blue  love green  quick blue  quick brown  sausages bacon  \
0          0           0           0            0               0   
1          1           0           0            0               0   
2          0           0           0            1               0   
3          0           0           0            0               0   
4          0           1           0            0               1   
5          0           0           1            0               0   
6          0           0           0            0               0   
7          0           0           0            0               0   

   sausages ham  sky beautiful  sky blue  toast beans  
0             0              0         1            0  
1             0              0         0            0  
2             0              0         0            0  
3             1              0         0            1  
4             0              0         0            0  
5             0              0         0            0  
6             0              1         1            0  
7             0              0         0            0  

[8 rows x 29 columns]

In [ ]:
# TF-IDF model
# TF-IDF stands for Term Frequency-Inverse Document Frequency, which uses a combination of two metrics in its computation, namely: term frequency (tf) & inverse document frequency (idf).
# Mathematically, tfidf = tf x idf
# Here, tfidf(w, D) is the TF-IDF score for word w in document D.
# The term tf(w, D) represents the term frequency of the word w in document D, which can be obtained from the Bag of Words model.
# The term idf(w, D) is the inverse document frequency for the term w, which can be computed as the log transform of the total number of documents in the corpus C divided by the document frequency of the word w, which is basically the frequency of documents in the corpus where the word w occurs.

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer(min_df=0., max_df=1., use_idf=True)
tv_matrix = tv.fit_transform(norm_corpus)
tv_matrix = tv_matrix.toarray()

vocab = tv.get_feature_names()
pd.DataFrame(np.round(tv_matrix, 2), columns=vocab)

bacon  beans  beautiful  blue  breakfast  brown   dog  eggs   fox  green  \
0   0.00   0.00       0.60  0.53       0.00   0.00  0.00  0.00  0.00   0.00   
1   0.00   0.00       0.49  0.43       0.00   0.00  0.00  0.00  0.00   0.00   
2   0.00   0.00       0.00  0.00       0.00   0.38  0.38  0.00  0.38   0.00   
3   0.32   0.38       0.00  0.00       0.38   0.00  0.00  0.32  0.00   0.00   
4   0.39   0.00       0.00  0.00       0.00   0.00  0.00  0.39  0.00   0.47   
5   0.00   0.00       0.00  0.37       0.00   0.42  0.42  0.00  0.42   0.00   
6   0.00   0.00       0.36  0.32       0.00   0.00  0.00  0.00  0.00   0.00   
7   0.00   0.00       0.00  0.00       0.00   0.45  0.45  0.00  0.45   0.00   

    ham  jumps  kings  lazy  love  quick  sausages   sky  toast  today  
0  0.00   0.00   0.00  0.00  0.00   0.00      0.00  0.60   0.00    0.0  
1  0.00   0.00   0.00  0.00  0.57   0.00      0.00  0.49   0.00    0.0  
2  0.00   0.53   0.00  0.38  0.00   0.38      0.00  0.00   0.00    0.0  
3  0.32   0.00   0.38  0.00  0.00   0.00      0.32  0.00   0.38    0.0  
4  0.39   0.00   0.00  0.00  0.39   0.00      0.39  0.00   0.00    0.0  
5  0.00   0.00   0.00  0.42  0.00   0.42      0.00  0.00   0.00    0.0  
6  0.00   0.00   0.00  0.00  0.00   0.00      0.00  0.72   0.00    0.5  
7  0.00   0.00   0.00  0.45  0.00   0.45      0.00  0.00   0.00    0.0

In [ ]:
# Document similarity
# It is the process of using a distance/similarity based metric that can be used to identify how similar a text document is with any other document(s) based on features extracted from the documents like bag of words/tf-idf.

In [12]:
# From the result, we can see that document 0 is quite similar to document 1 & document 6
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tv_matrix)
similarity_df = pd.DataFrame(similarity_matrix)
similarity_df

0         1         2         3         4         5         6  \
0  1.000000  0.820599  0.000000  0.000000  0.000000  0.192353  0.817246   
1  0.820599  1.000000  0.000000  0.000000  0.225489  0.157845  0.670631   
2  0.000000  0.000000  1.000000  0.000000  0.000000  0.791821  0.000000   
3  0.000000  0.000000  0.000000  1.000000  0.506866  0.000000  0.000000   
4  0.000000  0.225489  0.000000  0.506866  1.000000  0.000000  0.000000   
5  0.192353  0.157845  0.791821  0.000000  0.000000  1.000000  0.115488   
6  0.817246  0.670631  0.000000  0.000000  0.000000  0.115488  1.000000   
7  0.000000  0.000000  0.850516  0.000000  0.000000  0.930989  0.000000   

          7  
0  0.000000  
1  0.000000  
2  0.850516  
3  0.000000  
4  0.000000  
5  0.930989  
6  0.000000  
7  1.000000

In [ ]:
# Clustering using document similarity features
# K-means clustering to cluster/group these documents based on their similarity based feature representations. 
# In K-means clustering, we have an input parameter k, which specifies the number of clusters it will output using the document features. 
# This clustering method is a centroid based clustering method, where it tries to cluster these documents into clusters of equal variance. 
# It tries to create these clusters by minimizing the within-cluster sum of squares measure, also known as inertia.

In [13]:
from sklearn.cluster import KMeans

km = KMeans(n_clusters=3, random_state=0)
km.fit_transform(similarity_matrix)
cluster_labels = km.labels_
cluster_labels = pd.DataFrame(cluster_labels, columns=['ClusterLabel'])
pd.concat([corpus_df, cluster_labels], axis=1)

Document  \
0                                      The sky is blue and beautiful.   
1                                   Love this blue and beautiful sky!   
2                        The quick brown fox jumps over the lazy dog.   
3  A king's breakfast has sausages, ham, bacon, eggs, toast and beans   
4                         I love green eggs, ham, sausages and bacon!   
5                    The brown fox is quick and the blue dog is lazy!   
6            The sky is very blue and the sky is very beautiful today   
7                         The dog is lazy but the brown fox is quick!   

  Category  ClusterLabel  
0  weather             2  
1  weather             2  
2  animals             1  
3     food             0  
4     food             0  
5  animals             1  
6  weather             2  
7  animals             1